### ISSUE TITLE
Question - Support of processing.guarantee

### ISSUE THREAD

**Issue by GeoffreyHervet** [nodefluent/kafka-streams#119]
Hello,

Will `processing.guarantee` be supported in a future version of `kafka-streams`  https://docs.confluent.io/current/streams/developer-guide/config-streams.html#processing-guarantee ?

**Comment by krystianity** [comment]
This depends on the underlying Kafka client which at the lowest point is node-rdkafka.
However if you are building mission critical processing solutions I would suggest sticking to either the Java/Scala Kafka-Streams Library or node-sinek without the most.js stream layer.
