### ISSUE TITLE
Updating sinek to 8.0.0

### ISSUE THREAD

**Issue by elimenko** [nodefluent/kafka-streams#139]
Hey, I'm curios, do you have a plan to update to sinek 8.0.0? The reason why I'm asking is because in sinek@8.0.0 `node-rdkafka` is marked as optional dependency, and it causing a lot of troubles in building our alpine docker image. So It would be nice to get rid of it

**Comment by emahnovets** [comment]
We are facing the same issue with alpine images

**Comment by krystianity** [comment]
Hi guys, will do this very soon.

**Comment by elimenko** [comment]
@krystianity That's great to hear! Will look forward for the update

**Comment by tonycapone** [comment]
Having the same issue here. Thanks for working on this.
