### ISSUE TITLE
uuid is not a devDependency

### ISSUE THREAD

**Issue by pranaygp** [nodefluent/kafka-streams#141]
It is used here:
https://github.com/nodefluent/kafka-streams/blob/b8fe8eb011c0319ab4136e8664131aac13c4bf59/lib/dsl/StreamDSL.js#L6

but it's listed as a devDependency
https://github.com/nodefluent/kafka-streams/blob/b8fe8eb011c0319ab4136e8664131aac13c4bf59/package.json#L79

this breaks yarn 2

**Comment by rob3000** [comment]
Thanks @pranaygp Have just fixed this up: https://github.com/nodefluent/kafka-streams/pull/157
