### ISSUE TITLE
Move from travis to github actions

### ISSUE THREAD

**Issue by wtrocki** [nodefluent/kafka-streams#154]
I wanted to fix build process but this can be great chance to move to more robust build system

**Comment by rob3000** [comment]
@wtrocki any chance we could use github actions instead? I've added some for the documentation here: https://github.com/nodefluent/kafka-streams/blob/master/.github/workflows/documentation.yml

**Comment by wtrocki** [comment]
Sounds like plan

**Comment by rob3000** [comment]
Happy for you to take this one @wtrocki

**Comment by rob3000** [comment]
Hey @wtrocki , So i've been playing with github actions to try to build node-sinek containers with no luck: https://github.com/rob3000/node-sinek/runs/983832064?check_suite_focus=true
For some reason the containers dont stay alive long enough for the tests to start running. Happy for you to try move to circleCI if you're still keen for that?

**Comment by wtrocki** [comment]
Hi

I spent a lot of time trying to SSH into container.
Preferred way to do it in GitHub actions is to create service that is container based. I had no luck with docker-compose - there is no easy way to get logs from this so I guess we can have service approach instead. 

As for CircleCI it will be much easier but I prefer to do GitHub actions. On holidays for next 4 days. I think I will be able to get that done after.

**Comment by rob3000** [comment]
Hey @wtrocki  that's the approach it took in creating service containers but for some reason they dont stay up
