### ISSUE TITLE
Can't get examples to work

### ISSUE THREAD

**Issue by ls12styler** [nodefluent/kafka-streams#30]
Hi,

I've been trying to get the examples provided in the repository to work on my local machine without any luck. Whenever I try and start any of them I'm presented with the following error:

```➜  kafka-streams git:(master) ✗ node examples/consumeFromTopic.js
INFO @ 2017-10-26T08:14:36.640Z : [log4bro] Logger is: in-prod=false, in-docker:false, level=INFO, skipDebug=false
Unhandled rejection Error: One of the following: zkConStr or kafkaHost must be defined.
```

It's using the `test-config.js` provided by the repository, which has `kafkaHost` defined & uncommented by default. Even commenting out Kafka and using ZK has the same issue.

Any advice?

Thanks.

**Comment by krystianity** [comment]
Hey @ls12styler the reason for that is, that the import of `test/test-config.js` actually results in an object with a native and a js configuration but you can only pass a single configuration, either javascript or native, to the KafkaStreams factory constructor.

I am sorry that I forgot to update the examples-config-require after the 3.0.0 release.
I have corrected the require in all examples via `const {nativeConfig: config} = require("./../test/test-config.js");`

**Comment by krystianity** [comment]
If you cannot use the native client (which you should, if possible) you can simply use the Javascript client via `const {config} = require("./../test/test-config.js");`

**Comment by ls12styler** [comment]
Ah! Not a problem. Thanks for updating.
