### ISSUE TITLE
Question: Specifying a key when producing to a topic

### ISSUE THREAD

**Issue by nabeelz6** [nodefluent/kafka-streams#33]
Hi,

I'm using ```node-rdkafka``` client and would like to a specify a key when producing to a topic. Your example ```produceToTopic.js``` seems to generate a random key for each message.

Thanks.

**Comment by nabeelz6** [comment]
@krystianity - Any thoughts on this? Does this library not support setting/reading from an actual key rather than the look for a key inside body of the message? 

Looks like library is setting null for the key when producing:
https://github.com/nodefluent/kafka-streams/blob/master/lib/StreamDSL.js#L844

**Comment by krystianity** [comment]
Hi @nabeelz6 you are right, the focus is set on building key and value pairs across message values currently - I adapt the API to be more equal to the key/value approach in confluents version in the future, but I do not have plans for that now.

I could add a feature that would use a "_key" or "_partition" field in the payload of stream events to choose the correct partition and key when producing through node-kafka-streams in the next release.
That should help you and others who are trying to produce deterministically or with a key at all. (I would remove the fields right before producing the message value to kafka, so it should integrate seemlessly)

**Comment by nabeelz6** [comment]
Thanks @krystianity. As a follow-up question related to keys, it does not look like that `innerJoin` method on two streams supports writing to the output only if both stream A and stream B have the same key (i.e. key can be anything)?

I looked through your ```Join.test.js``` sample and it only lets you write to the output if a particular key (known in advance) was seen in both streams, but not for any keys which appeared in both of the streams.

Is that something that's on your backlog?

**Comment by krystianity** [comment]
FYI: We are working on a new release that treats Keys and Values of Kafka Messages just as the official Java Version does it. Please be patient. It will also allow to define partitions and keys during pipes to output topics.
