### ISSUE TITLE
How to specify a key to stream's messages from .map method

### ISSUE THREAD

**Issue by vlad0337187** [nodefluent/kafka-streams#36]
Hello.

Here in example, while processing message in .map() method, key and value were added only to value:
https://github.com/nodefluent/kafka-streams/blob/master/examples/fieldSum.js#L12

Also I din't find in source code place, where key for message can be specified.
For example:
https://github.com/nodefluent/kafka-streams/blob/master/lib/StreamDSL.js#L104
https://github.com/nodefluent/kafka-streams/blob/master/lib/KStream.js#L95
, there is only 'value' parameter for sending messages.

But key is present in received message object.

Is there any way to specify a key for sent message ?

Thank you.

**Comment by ruleb** [comment]
It seems this library is not correctly implemented, it's not using the keys available on the kafka message, but instead expecting you put the key on the kafka value. 
his invalidates usage of topic compaction and more.

We've fallen back to a standard node-rdkafka implementation, where kafka message keys are available.

**Comment by krystianity** [comment]
As mentioned [here](https://github.com/nodefluent/kafka-streams/issues/33) this lib currently more or less irgnores message keys. I will release a refactored version which treats keys equally to the Java version, but I have no ETA; as a few other projects have a higher PRIO atm.

**Comment by krystianity** [comment]
FYI: We are working on a new release that treats Keys and Values of Kafka Messages just as the official Java Version does it. Please be patient. It will also allow to define partitions and keys during pipes to output topics.
