### ISSUE TITLE
Commit offset only after processing and producing to a different topic was successful

### ISSUE THREAD

**Issue by nabeelz6** [nodefluent/kafka-streams#42]
Hi,

I have the following Stream processing use case:
1) Consume a message
2) Do some processing on that message
3) Produce the result to a different topic

After step 3 is successful (i.e. producer message got successfully written to Kafka and acknowledged), I'd like to move the offset for the consumer but not before. 

If I use the [.map/.to](https://github.com/nodefluent/kafka-streams/blob/master/examples/wordCount.js#L26-L32) parts of this library, does this library automatically (or through configuration) update the offset  only AFTER produce was successful? Or do I have to manually call the Native [consumer.commitMessage() within node-rdkafka](https://github.com/Blizzard/node-rdkafka#standard-api-1) which would require listening on producer's delivery-reports event too?

Thanks!

**Comment by nabeelz6** [comment]
NOTE: I asked the same question for node-rdkafka [here](https://github.com/Blizzard/node-rdkafka/issues/346). I'm hoping this library has a way to make it easier :)

**Comment by krystianity** [comment]
Hi @nabeelz6 this is not possible with node-kafka-streams currently, although the behaviour might be similar in the backpressure mode. I would advice you to take a look at the 1:1 consumer mode of sinek https://github.com/nodefluent/node-sinek/blob/master/lib/librdkafka/README.md#consumer-modes

**Comment by fbunau** [comment]
@krystianity Hi, I am a bit confused by the usage of "enable.auto.commit" together with the library. Do you recommend on setting this to true ? or to false, and if on false, how would you manually commit the offset, once you are fairly safe and done with processing.

I have a asyncMap that could fail, and want to commit only when I'm fairly sure I'm done. perhaps a relaxation of the original OP constraint of when you are sure the message was sent to the output topic, but nevertheless on a similar idea track.

Can you give a few words please on how "kafka-streams" library deals with the commit lifecycle.

Thanks in advance !
