### ISSUE TITLE
node-rdkafka 

### ISSUE THREAD

**Issue by tannad** [nodefluent/kafka-streams#44]
Hi,

I am using node-rdkafka with SASL Kerberos, I would like to use the avro schema with it but it doesn't seem to support it, does kafka-streams support avro and is it production ready?

Looking forward to hear from you. Thank you in advance.

Best regards,
D Tanna

**Comment by krystianity** [comment]
@tannad kafka-streams uses node-rdkafka in sinek as native-client as well.
