### ISSUE TITLE
Can the map function do async work?

### ISSUE THREAD

**Issue by yashgt** [nodefluent/kafka-streams#60]
Hi,

Is it possible to do a DB lookup in the function that is passed to map? DB lookup will mean async calls to the DB. This is different in JS than in Java, hence the question.

-Yash

**Comment by krystianity** [comment]
Hi @yashgt , yes this is possible, but not through the `map` function itself.
What you can do is: Simply return a `Promise` from your map function and call `awaitPromises` afterwards. As shown in the example [here](https://github.com/nodefluent/kafka-streams/blob/master/examples/consumeOneProduceTwo.js#L18)

But keep in mind, that node-kafka-streams uses push streams, this means that there is no backpressure in the stream itself, which means that, depending on the amount of messages you are consuming and the latency + processing time that you database needs, you might run into memory problems - though it is possible to handle this with an appropriate consumer configuration [see this](https://github.com/nodefluent/node-sinek/tree/master/lib/librdkafka#our-experience), as well as deploying enough instances of your streaming service to spread the pressure.
