### ISSUE TITLE
Is possible to branch a stream?

### ISSUE THREAD

**Issue by Moisessoares** [nodefluent/kafka-streams#67]
It's possible to branch a stream, like java counterpart?

KStream<String, Long> stream = ...;
KStream<String, Long>[] branches = stream.branch(
    (key, value) -> key.startsWith("A"), /* first predicate  */
    (key, value) -> key.startsWith("B"), /* second predicate */
    (key, value) -> true                 /* third predicate  */
  );

// KStream branches[0] contains all records whose keys start with "A"
// KStream branches[1] contains all records whose keys start with "B"
// KStream branches[2] contains all other records

// Java 7 example: cf. `filter` for how to create `Predicate` instances

**Comment by krystianity** [comment]
@Moisessoares I will add this in a smaller new release until the end of the week.

**Comment by Moisessoares** [comment]
any news? 
do you need any kind of help?

**Comment by krystianity** [comment]
Sry @Moisessoares took a bit longer than expected, as I also had to update sinek and kafka-connect first. I also shipped typescript declarations as well as your branching in kafka-streams@4.6.0
A KStream instance now supports: `branch(preds: (message: any) => boolean[]): KStream[];`

I have added a unit test for the branching, solved by multicasting and adding a filter while mapping, however I have not yet been able to test it on a live broker, especially producing `.to()` a kafka topic from the branched streams. Let me know, if you need help.
