### ISSUE TITLE
Partitioner?

### ISSUE THREAD

**Issue by paambaati** [nodefluent/kafka-streams#68]
@krystianity I'm using the native producer, and have set up my options like this -

```
"options": {
      "noptions": {
        "metadata.broker.list": "...",
		"...": "..."
      },
      "tconf": {
        "partitioner": "murmur2"
      }
}
```

The `murmur2` partitioner doesn't seem to work, and all my messages (with unique-enough keys) end up on partition 0. Is this the correct way of doing this?

**Comment by krystianity** [comment]
Hi @paambaati did you also specify the partition count on `.to("output-topic", 30);` ?

The default value is 1, which will result in every message being produced to partition 0.
If you pass e.g. 30, it the messages will be spread across all partitions depending on the murmur2 of the key deterministically. (If you dont pass the murmur2 options, mumur3 is used as a default instead)

If in the end of your stream you are dealing with message objects (events are objects containing key and value, you can also specific a partition field and set the partitions on your own).

**Comment by paambaati** [comment]
@krystianity Thanks, that worked!
