### ISSUE TITLE
How do I produce to multiple topics?

### ISSUE THREAD

**Issue by sshaginyan** [nodefluent/kafka-streams#85]
I want to consume from a single topic and produce to multiple topics.

```javascript
const { KafkaStreams } = require('kafka-streams');

const kafkaStreams = new KafkaStreams({
    kafkaHost: "127.0.0.1:32771",
    logger: {
      debug: msg => console.log(msg),
      info: msg => console.log(msg),
      warn: msg => console.log(msg),
      error: msg => console.error(msg)
    },
    groupId: "kafka-streams-test",
    clientName: "kafka-streams-test-name",
    workerPerPartition: 1,
    options: {
        sessionTimeout: 8000,
        protocol: ["roundrobin"],
        fromOffset: "earliest",
        fetchMaxBytes: 1024 * 100,
        fetchMinBytes: 1,
        fetchMaxWaitMs: 10,
        heartbeatInterval: 250,
        retryMinTimeout: 250,
        autoCommit: true,
        autoCommitIntervalMs: 1000,
        requireAcks: 1,
        ackTimeoutMs: 100,
        partitionerType: 3
    }
});

const stream = kafkaStreams.getKStream('in');

const x = stream.branch([()=>{ return true; }, ()=>{ return true; }]);

x[0]
  .mapJSONConvenience()
  .mapWrapKafkaValue()
  .tap(console.log)
  .wrapAsKafkaValue()
  .to('out', 1, 'buffer');

x[1]
  .mapJSONConvenience()
  .mapWrapKafkaValue()
  .tap(console.log)
  .wrapAsKafkaValue()
  .to('test', 2, 'buffer');

stream.start().then(() => {
    console.log("stream started, as kafka consumer is ready.");
}, error => {
    console.log("streamed failed to start: " + error);
});
```

I'm using `./kafka-console-consumer --bootstrap-server 127.0.0.1:32771 --topic out` and `./kafka-console-consumer --bootstrap-server 127.0.0.1:32771 --topic test` to listen to my two outgoing streams. I can consuming data from my `out` topic but I'm only receiving `"[object Object]"` from my test topic.

**Comment by yogereddy** [comment]
@sshaginyan I'm running into the same issue, where you able to find a resolution?

**Comment by krystianity** [comment]
Will add this as example tomorrow.

**Comment by krystianity** [comment]
@yogereddy @sshaginyan I have added your question as example: https://github.com/nodefluent/kafka-streams/blob/master/examples/consumeOneProduceTwoTopics.js

Please make sure to upgrade to kafka-streams@4.10.0 before trying it out.

One of the main reasons, you were experiencing [Object object] is that the old KStream.branch was creating stream$ clones, but it was not creating clones of the stream events, which caused your secondary function calls to mutate all events twice with `mapWrapKafkaValue ` for example. I have changed this now - branch will create cloned streams with (deeply) cloned events.
