### ISSUE TITLE
supported kerberos?

### ISSUE THREAD

**Issue by yuu2lee4** [nodefluent/kafka-streams#9]
supported kerberos?

**Comment by krystianity** [comment]
Hi Yuu2lee4,

I guess you are asking if the underlying Kafka Consumer/Producer supports "SASL+Kerberos"; kafka-streams uses "node-kafka" which supports SSL; however it does not support kerberos as of today. See https://github.com/SOHU-Co/kafka-node/issues/511

**Comment by yuu2lee4** [comment]
Maybe could do it based on those modules:
https://github.com/adaltas/node-krb5
https://www.npmjs.com/package/krb5

**Comment by krystianity** [comment]
The lib will get an additional lbrdkafka mode, which will bring SASL and Kerberos very soon.

**Comment by yuu2lee4** [comment]
I already found a [module](https://github.com/Blizzard/node-rdkafka) suportted SASL.

**Comment by krystianity** [comment]
Yeah...but that is a kafka-client, not a kafka-streams implementation ;)

**Comment by krystianity** [comment]
kafka-streams version >= 3.0.0 supports SSL, SASL and Kerberos.
