### ISSUE TITLE
Allow injecting custom Kafka client

### ISSUE THREAD

**Issue by Nevon** [nodefluent/kafka-streams#95]
I'm one of the developers of [kafkajs](https://kafka.js.org). I've been wanting to provide a Kafka Streams-like API on top of it for some time now, but looking at this library, it looks like the interface between it and the underlying Kafka client library is pretty small, so it should be perfectly possible to allow the user to inject their own client, provided that it implements the expected interface.

Would you be open to accepting a PR that adds a `config.clientFactory` option that would accept a function returning something extending `KafkaClient`, which would be used instead of instantiating `JSKafkaClient`/`NativeKafkaClient` when provided?

**Comment by krystianity** [comment]
Hi @Nevon we use https://github.com/nodefluent/node-sinek to bundle multiple kafka-clients in similar interfaces under a single module. Feel free to open a PR for kafkajs there.

**Comment by wtrocki** [comment]
@Nevon Thank you for logging the issue. As this is `node-sinek` issue I'm going to close it. 
Feel free to reopen it if needed.

**Comment by rob3000** [comment]
Just thought i'd also mention @Nevon that we do currently support kafkaJS in `node-sinek` and have just dropped support for previous alternatives. Its currently being updated in this pr here: https://github.com/nodefluent/node-sinek/pull/154
